site_name: Ricardo Domenzain
site_description: About this Github account of Ricardo Domenzain
site_dir: public
copyright: Copyright &copy; R. Domenzain 2022

repo_url: https://github.com/rdomenzain/rdomenzain.git

# nav:
#  - Home: README.md

plugins:
    - search
    - glightbox
theme:
    name: material
    icon:
        logo: octicons/rocket-24
    palette:
        primary: #01304f
    features:
        - navigation.tabs
        - instant

extra:
    manifest: "manifest.webmanifest"
    social:
        - icon: material/github
          link: https://github.com/rdomenzain
        - icon: material/home
          link: https://github.com/rdomenzain/rdomenzain

markdown_extensions:
    - toc:
          permalink: true
    - admonition
    - abbr
    - attr_list
    - codehilite
    - def_list
    - footnotes
    - md_in_html
    - meta
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
