site_name: Ricardo Domenzain
site_description: About this Github account of Ricardo Domenzain
docs_dir: './docs/'
site_dir: '.'
copyright: Copyright &copy; R. Domenzain 2022

repo_url: https://github.com/rdomenzain/rdomenzain
repo_name: rdomenzain

# nav:
#  - Home: README.md

plugins:
    - search:
        lang: en
    - glightbox
    - material-relative-language-selector
theme:
    name: material
    language: en
    icon:
        logo: octicons/rocket-24
        repo: fontawesome/brands/github
    font:
      text: Ubuntu
      code: Source Code Pro
    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: teal
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    features:
        - navigation.tabs
        - instant

extra:
    manifest: "manifest.webmanifest"
    generator: false
    social:
        - icon: material/home
          link: https://rdomenzain.github.io/rdomenzain/
        - icon: material/github
          link: https://github.com/rdomenzain
        - icon: material/linkedin
          link: https://linkedin.com/in/rdomenzain
    consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.

markdown_extensions:
    - toc:
          permalink: true
    - admonition
    - abbr
    - attr_list
    - codehilite
    - def_list
    - footnotes
    - md_in_html
    - meta
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
